apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-deploy
spec:
  maxReplicas: 8
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: webapp-deploy
  targetCPUUtilizationPercentage: 40
