apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: webapp
spec:
  ports:
    - port: 3306
  selector:
    app: webapp
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: webapp
	
spec:
  selector:
    matchLabels:
      app: webapp
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp
        tier: mysql
    spec:
      containers:
      - image: saravananmoorthy/mysqldbrepo:0.2
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
			  
		ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: my-data
            mountPath: "/var/lib/mysql"
      restartPolicy: Always
      volumes:
        - name: my-data
          persistentVolumeClaim:
            claimName: db-volume