kind: PersistentVolume
apiVersion: v1
metadata:
 name: mysql-pv
 labels:
  type: local
spec:
 storageClassName: mystorage
 capacity:
   storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/mysql_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume
spec:
  storageClassName: mystorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
                    